title:            Conversational Git
description:      A friendly Git introduction
#url: http://blog.anvard.org

owner:
  name:           Alan Hohn

timezone:    America/Chicago
future:      true
pygments:    true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

